### ISSUE TITLE
Eror1.php

### ISSUE THREAD

**Issue by yogi211517** [rockcesar/PiNetworkDevelopments#2]
in developing a payment system through the pi sdk, I followed your source code, but when clicking donate didn't work, the explanation is like this, please help me

**Comment by rockcesar** [comment]
You need to use the right API Key, check where it says, $apps['auth_app1'] = 'Key <your Server API Key>';.

Change auth_app1 by auth_example, in the https://github.com/rockcesar/PiNetworkDevelopments/blob/master/server1.php.

auth_example is in https://github.com/rockcesar/PiNetworkDevelopments/blob/master/piapp-example/main.html

**Comment by yogi211517** [comment]
it's the same as that, should it be integrated in the odoo website pi network game our app?L

**Comment by rockcesar** [comment]
You can create a module and inherit it from website_pinetwork_odoo in Odoo
Apps:

https://apps.odoo.com/apps/modules/15.0/website_pinetwork_odoo/

**Comment by yogi211517** [comment]
it's the same as that, should it be integrated in the odoo website pi network game our app?

**Comment by rockcesar** [comment]
Browse your Odoo version, for the App:

https://apps.odoo.com/apps/modules/14.0/website_pinetwork_odoo/

**Comment by yogi211517** [comment]
whether paid or not

**Comment by rockcesar** [comment]
Not paid, our modules are AGPLv3.

**Comment by yogi211517** [comment]
Thangkyou very much🙏

**Comment by yogi211517** [comment]
how to integrate api key on pi network odo website

**Comment by yogi211517** [comment]
please teach me how to integrate piapp_example in odoo

**Comment by rockcesar** [comment]
Check this video:

https://youtu.be/9KqcyAoCZzo?t=943

**Comment by yogi211517** [comment]
Traceback (most recent call last):
  File "C:\Program Files\odoo15\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\odoo15\server\odoo\http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files\odoo15\server\odoo\http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\odoo15\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\odoo15\server\odoo\http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\odoo15\server\odoo\http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files\odoo15\server\odoo\http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\odoo15\server\odoo\addons\web\controllers\main.py", line 1339, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\odoo15\server\odoo\addons\web\controllers\main.py", line 1327, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\odoo15\server\odoo\api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files\odoo15\server\odoo\api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "C:\Program Files\odoo15\server\odoo\addons\base\models\ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files\odoo15\server\odoo\addons\base\models\ir_module.py", line 483, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files\odoo15\server\odoo\addons\base\models\ir_module.py", line 600, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files\odoo15\server\odoo\modules\registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "C:\Program Files\odoo15\server\odoo\modules\loading.py", line 476, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files\odoo15\server\odoo\modules\loading.py", line 365, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files\odoo15\server\odoo\modules\loading.py", line 179, in load_module_graph
    load_openerp_module(package.name)
  File "C:\Program Files\odoo15\server\odoo\modules\module.py", line 396, in load_openerp_module
    __import__('odoo.addons.' + module_name)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\odoo15\server\odoo\http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files\odoo15\server\odoo\http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ModuleNotFoundError: No module named 'odoo.addons.website_pinetwork_odoo-15'

**Comment by yogi211517** [comment]
When I install the caption like that, please help me

**Comment by rockcesar** [comment]
Rename from website_pinetwork_odoo-15 to website_pinetwork_odoo_15 or
website_pinetwork_odoo

**Comment by rockcesar** [comment]
You need to check the code.

App code is the name of the app to send through the system, to approve or
complete payment. And Admin Key is the same for Api Key in develop.pi.

Take a look for all the code, all is in Odoo.

--
Especialista Cesar Cordero Rodriguez

**Comment by yogi211517** [comment]
how much do you give me an example of what

**Comment by yogi211517** [comment]
do you want to make me a payment using the sdk Pi payment in my online shop, if you want I will pay you
